### ISSUE TITLE
wgs-torch:control_diffusion

### ISSUE THREAD

**Issue by KunpengZhaoo** [WGS-note/finetune_stable_diffusion#1]
请问我在运行时出现了以下问题：
Unable to find image 'wgs-torch:control_diffusion' locally
docker: Error response from daemon: pull access denied for wgs-torch, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
这个wgs-torch:control_diffusion是镜像名字吗，我查看了Dockerfile为什么创建wgs-torch:control_diffusion以及上面的安装都注释掉了

万分感谢！

**Comment by WGS-note** [comment]
是镜像名字

**Comment by KunpengZhaoo** [comment]
你好


感谢回复
我通过Dockerfile构建镜像（wgs-torch:control_diffusion）的时候发现deepspeed是被删除了吗

The command '/bin/sh -c pip install -i https://pypi.tuna.tsinghua.edu.cn/simple deepspeed' returned a non-zero code: 1

有什么解决办法呢




感谢



















在 2023-12-11 15:34:02，"WGS" ***@***.***> 写道：

是镜像名字
